# Data Analysis: Exploring eBay Car Sales Data

In this project, we analyze a dataset of used car listings from *eBay Kleinanzeigen*, a classifieds section of the German eBay website.

### Our goals

Our primary goal is to **clean the data** and **perform an initial analysis** to understand the characteristics of the used car market in Germany.

### Dataset Description

The dataset includes various attributes such as the car's price, brand, registration year, mileage (odometer), and fuel type, providing a realistic look at scraped web data that requires significant cleaning.

## 1. Loading the Dataset

To begin our analysis, we will import the necessary libraries—**pandas** and **NumPy**—and load the `autos.csv` dataset. 

Because this dataset was scraped from the German eBay website, it contains special characters that aren't compatible with the standard `UTF-8` encoding. We will use the `latin1` encoding to ensure the data loads correctly.

In [1]:
import pandas as pd
import numpy as np

# Attempt to read the CSV file
# We use 'latin1' encoding as the default 'UTF-8' may throw an error for this specific file
autos = pd.read_csv('autos.csv', encoding='latin1')

autos  # Display the first and last few rows of the dataframe

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,2016-03-27 14:38:19,Audi_Q5_3.0_TDI_qu._S_tr.__Navi__Panorama__Xenon,privat,Angebot,"$24,900",control,limousine,2011,automatik,239,q5,"100,000km",1,diesel,audi,nein,2016-03-27 00:00:00,0,82131,2016-04-01 13:47:40
49996,2016-03-28 10:50:25,Opel_Astra_F_Cabrio_Bertone_Edition___TÜV_neu+...,privat,Angebot,"$1,980",control,cabrio,1996,manuell,75,astra,"150,000km",5,benzin,opel,nein,2016-03-28 00:00:00,0,44807,2016-04-02 14:18:02
49997,2016-04-02 14:44:48,Fiat_500_C_1.2_Dualogic_Lounge,privat,Angebot,"$13,200",test,cabrio,2014,automatik,69,500,"5,000km",11,benzin,fiat,nein,2016-04-02 00:00:00,0,73430,2016-04-04 11:47:27
49998,2016-03-08 19:25:42,Audi_A3_2.0_TDI_Sportback_Ambition,privat,Angebot,"$22,900",control,kombi,2013,manuell,150,a3,"40,000km",11,diesel,audi,nein,2016-03-08 00:00:00,0,35683,2016-04-05 16:45:07
49999,2016-03-14 00:42:12,Opel_Vectra_1.6_16V,privat,Angebot,"$1,250",control,limousine,1996,manuell,101,vectra,"150,000km",1,benzin,opel,nein,2016-03-13 00:00:00,0,45897,2016-04-06 21:18:48

In [2]:
# Display summary information and the first 5 rows
print(autos.info())
autos.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   dateCrawled          50000 non-null  object
 1   name                 50000 non-null  object
 2   seller               50000 non-null  object
 3   offerType            50000 non-null  object
 4   price                50000 non-null  object
 5   abtest               50000 non-null  object
 6   vehicleType          44905 non-null  object
 7   yearOfRegistration   50000 non-null  int64
 8   gearbox              47320 non-null  object
 9   powerPS              50000 non-null  int64
 10  model                47242 non-null  object
 11  odometer             50000 non-null  object
 12  monthOfRegistration  50000 non-null  int64
 13  fuelType             45518 non-null  object
 14  brand                50000 non-null  object
 15  notRepairedDamage    40171 non-null  object
 16  dateCreated          50000 non-null  object
 17  nrOfPictures         50000 non-null  int64
 18  postalCode           50000 non-null  int64
 19  lastSeen             50000 non-null  object
dtypes: int64(5), object(15)
memory usage: 7.6+ MB
None

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,odometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

## 2. Initial Observations

After inspecting the data, several key observations can be made:

1. **Column Names**: The dataset uses CamelCase (e.g., `yearOfRegistration`) instead of Python's preferred snake_case (e.g., `year_of_registration`). Some column names could also be more descriptive.
2. **Missing Values**: Columns such as `vehicleType`, `gearbox`, `model`, `fuelType`, and `notRepairedDamage` contain null values.
3. **Data Types**: 
    * The `price` and `odometer` columns are stored as text (strings) because they likely include characters like `$` or `km`. We will need to clean these and convert them to numeric types.
    * Dates (`dateCrawled`, `dateCreated`, `lastSeen`) are currently strings and will need to be converted to actual datetime objects for analysis.
4. **General Content**: Some columns like `seller` and `offerType` appear to have mostly identical values, which might make them less useful for analysis.

## 3. Cleaning Column Names

In this step, we will clean the column headers to make the dataset easier to work with in Python. The changes will include:

1.  **Converting from camelCase to snake_case**: Following Python's PEP 8 style guide, we will replace names like `dateCrawled` with `date_crawled`. This makes the code more readable and consistent.
2.  **Renaming for Clarity**: Based on the data dictionary, we will rename several columns to be more descriptive:
    * `yearOfRegistration` → `registration_year`
    * `monthOfRegistration` → `registration_month`
    * `notRepairedDamage` → `unrepaired_damage`
    * `dateCreated` → `ad_created`

By standardizing the headers now, we prevent errors in future steps and make it easier to reference columns using dot notation or bracket indexing.

In [3]:
# Print the existing column names
print(autos.columns)

# Create a modified list of column names
new_columns = [
    'date_crawled', 'name', 'seller', 'offer_type', 'price', 'abtest',
    'vehicle_type', 'registration_year', 'gearbox', 'power_ps', 'model',
    'odometer', 'registration_month', 'fuel_type', 'brand',
    'unrepaired_damage', 'ad_created', 'nr_of_pictures', 'postal_code',
    'last_seen'
]

# Assign the new names back to the dataframe
autos.columns = new_columns

# Check the results
autos.head()

Index(['dateCrawled', 'name', 'seller', 'offerType', 'price', 'abtest',
       'vehicleType', 'yearOfRegistration', 'gearbox', 'powerPS', 'model',
       'odometer', 'monthOfRegistration', 'fuelType', 'brand',
       'notRepairedDamage', 'dateCreated', 'nrOfPictures', 'postalCode',
       'lastSeen'],
      dtype='object')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
0,2016-03-26 17:47:46,Peugeot_807_160_NAVTECH_ON_BOARD,privat,Angebot,"$5,000",control,bus,2004,manuell,158,andere,"150,000km",3,lpg,peugeot,nein,2016-03-26 00:00:00,0,79588,2016-04-06 06:45:54
1,2016-04-04 13:38:56,BMW_740i_4_4_Liter_HAMANN_UMBAU_Mega_Optik,privat,Angebot,"$8,500",control,limousine,1997,automatik,286,7er,"150,000km",6,benzin,bmw,nein,2016-04-04 00:00:00,0,71034,2016-04-06 14:45:08
2,2016-03-26 18:57:24,Volkswagen_Golf_1.6_United,privat,Angebot,"$8,990",test,limousine,2009,manuell,102,golf,"70,000km",7,benzin,volkswagen,nein,2016-03-26 00:00:00,0,35394,2016-04-06 20:15:37
3,2016-03-12 16:58:10,Smart_smart_fortwo_coupe_softouch/F1/Klima/Pan...,privat,Angebot,"$4,350",control,kleinwagen,2007,automatik,71,fortwo,"70,000km",6,benzin,smart,nein,2016-03-12 00:00:00,0,33729,2016-03-15 03:16:28
4,2016-04-01 14:38:50,Ford_Focus_1_6_Benzin_TÜV_neu_ist_sehr_gepfleg...,privat,Angebot,"$1,350",test,kombi,2003,manuell,0,focus,"150,000km",7,benzin,ford,nein,2016-04-01 00:00:00,0,39218,2016-04-01 14:38:50

## 4. Initial Exploration and Cleaning

Before proceeding with deep analysis, we use `df.describe()` to get an overview of the dataset. We are looking for:
* **Static Columns**: Features where almost all values are the same (low variance), which typically don't provide useful insights.
* **Hidden Numeric Data**: Numeric values currently stored as text because of symbols like `$` or `km`.
* **Anomalies**: Unusual distributions, such as columns that appear to be empty or have invalid data.

In [4]:
# Explore descriptive statistics for both numeric and categorical columns
autos.describe(include='all')

,date_crawled,name,seller,offer_type,price,abtest,vehicle_type,registration_year,gearbox,power_ps,model,odometer,registration_month,fuel_type,brand,unrepaired_damage,ad_created,nr_of_pictures,postal_code,last_seen
count,50000,50000,50000,50000,50000,50000,44905,50000.000000,47320,50000.000000,47242,50000,50000.000000,45518,50000,40171,50000,50000.0,50000.000000,50000
unique,48213,38754,2,2,2357,2,8,NaN,2,NaN,245,13,NaN,7,40,2,76,NaN,NaN,39481
top,2016-04-02 11:37:04,Ford_Fiesta,privat,Angebot,$0,test,limousine,NaN,manuell,NaN,golf,"150,000km",NaN,benzin,volkswagen,nein,2016-04-03 00:00:00,NaN,NaN,2016-04-07 06:17:27
freq,3,78,49999,49999,1421,25756,12859,NaN,36993,NaN,4024,32424,NaN,30107,10687,35232,1946,NaN,NaN,8
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2005.073280,NaN,116.355920,NaN,NaN,5.723360,NaN,NaN,NaN,NaN,0.0,50813.627300,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105.712813,NaN,209.216627,NaN,NaN,3.711984,NaN,NaN,NaN,NaN,0.0,25779.747957,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1000.000000,NaN,0.000000,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,0.0,1067.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1999.000000,NaN,70.000000,NaN,NaN,3.000000,NaN,NaN,NaN,NaN,0.0,30451.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2003.000000,NaN,105.000000,NaN,NaN,6.000000,NaN,NaN,NaN,NaN,0.0,49577.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008.000000,NaN,150.000000,NaN,NaN,9.000000,NaN,NaN,NaN,NaN,0.0,71540.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9999.000000,NaN,17700.000000,NaN,NaN,12.000000,NaN,NaN,NaN,NaN,0.0,99998.000000,NaN

### Observations and Cleaning Plan

Based on the summary above, we can conclude the following:

1.  **Drop Candidates**: The `seller` and `offer_type` columns contain nearly 100% identical values. Additionally, `nr_of_pictures` seems to contain only zeros. We will investigate these further.
2.  **Numeric Conversion**: The `price` and `odometer` columns are currently stored as `object` (text) due to the presence of symbols ($ and km) and commas.

**Cleaning Steps:**
* Remove the `$` and `,` characters from the `price` column and convert it to an integer.
* Remove the `km` and `,` characters from the `odometer` column, convert it to an integer, and rename it to `odometer_km` to preserve the unit information.

In [5]:
# Cleaning the 'price' column
autos["price"] = (autos["price"]
                  .str.replace("$", "")
                  .str.replace(",", "")
                  .astype(int)
                 )

# Cleaning the 'odometer' column
autos["odometer"] = (autos["odometer"]
                     .str.replace("km", "")
                     .str.replace(",", "")
                     .astype(int)
                    )

# Rename 'odometer' to 'odometer_km'
autos.rename({"odometer": "odometer_km"}, axis=1, inplace=True)

# Verify the result
autos[["price", "odometer_km"]].head()

   price  odometer_km
0   5000       150000
1   8500       150000
2   8990        70000
3   4350        70000
4   1350       150000

## 5. Exploring the Odometer and Price Columns

Now that we have converted the `price` and `odometer_km` columns to numeric types, we will examine them for **outliers**—values that are unrealistically high or low. These anomalies often occur due to data entry errors or issues with the original scraping process.

We will analyze the distributions and use the `df.between()` method to remove any data points that could skew our analysis.

In [6]:
# Exploring Odometer
print("Odometer Unique Values:", autos["odometer_km"].unique().shape[0])
print(autos["odometer_km"].describe())
print("\nOdometer Value Counts (Sorted):")
print(autos["odometer_km"].value_counts().sort_index(ascending=False).head())

# Exploring Price
print("\nPrice Unique Values:", autos["price"].unique().shape[0])
print(autos["price"].describe())
print("\nTop 10 Highest Prices:")
print(autos["price"].value_counts().sort_index(ascending=False).head(10))
print("\nTop 10 Lowest Prices:")
print(autos["price"].value_counts().sort_index(ascending=True).head(10))

Odometer Unique Values: 13
count     50000.000000
mean     125732.700000
std       40042.211706
min        5000.000000
25%      125000.000000
50%      150000.000000
75%      150000.000000
max      150000.000000
Name: odometer_km, dtype: float64

Odometer Value Counts (Sorted):
odometer_km
150000    32424
125000     5170
100000     2169
90000      1757
80000      1436
Name: count, dtype: int64

Price Unique Values: 2357
count    5.000000e+04
mean     9.840044e+03
std      4.811044e+05
min      0.000000e+00
25%      1.100000e+03
50%      2.950000e+03
75%      7.200000e+03
max      1.000000e+08
Name: price, dtype: float64

Top 10 Highest Prices:
price
99999999    1
27322222    1
12345678    3
11111111    2
10000000    1
3890000     1
1300000     1
1234566     1
999999      2
999990      1
Name: count, dtype: int64

Top 10 Lowest Prices:
price
0     1421
1      156
2        3
3        1
5        2
8        1
9        1
10       7
11       2
12       3
Name: count, dtype: int64

### Observations and Outlier Removal

**Odometer:**
The odometer values appear to be rounded, suggesting users chose from a pre-set list of options. The maximum value is 150,000 km and the minimum is 5,000 km. There are no obvious outliers here that need removal.

**Price:**
The price column, however, has several issues:
* There are **1,421** listings with a price of **\$0**. Since eBay is an auction/sales site, \$0 is not a realistic starting price and these rows should be removed.
* There are extreme high-end outliers, such as listings for **\$99,999,999** and **\$12,345,678**. 
* While some luxury cars (like Ferraris) can legitimately sell for high amounts, prices jump significantly after **\$350,000**. 

We will keep listings between **\$1** and **\$350,000**, as anything above that tends toward unrealistic "placeholder" numbers.

In [7]:
# Removing outliers in price
autos = autos[autos["price"].between(1, 350000)]

# Verify the new distribution
print(autos["price"].describe())

count     48565.000000
mean       5888.935591
std        9059.854754
min           1.000000
25%        1200.000000
50%        3000.000000
75%        7490.000000
max      350000.000000
Name: price, dtype: float64

## 6. Exploring the Date Columns

There are 5 columns in the dataset that represent date information. We can categorize them as follows:
* **Crawler Dates**: `date_crawled` and `last_seen`.
* **Website Dates**: `ad_created`, `registration_month`, and `registration_year`.

The crawler dates and `ad_created` are currently stored as strings. We will extract the date portion (the first 10 characters) to analyze the distribution of listings across the time the data was collected.

In [8]:
# Analyzing the distribution of date_crawled
print("Date Crawled Distribution:")
print(autos['date_crawled'].str[:10].value_counts(normalize=True, dropna=False).sort_index())

Date Crawled Distribution:
date_crawled
2016-03-05    0.025327
2016-03-06    0.014043
2016-03-07    0.036014
2016-03-08    0.033296
2016-03-09    0.033090
2016-03-10    0.032184
2016-03-11    0.032575
2016-03-12    0.036920
2016-03-13    0.015670
2016-03-14    0.036549
2016-03-15    0.034284
2016-03-16    0.029610
2016-03-17    0.031628
2016-03-18    0.012911
2016-03-19    0.034778
2016-03-20    0.037887
2016-03-21    0.037373
2016-03-22    0.032987
2016-03-23    0.032225
2016-03-24    0.029342
2016-03-25    0.031607
2016-03-26    0.032204
2016-03-27    0.031092
2016-03-28    0.034860
2016-03-29    0.034099
2016-03-30    0.033687
2016-03-31    0.031834
2016-04-01    0.033687
2016-04-02    0.035478
2016-04-03    0.038608
2016-04-04    0.036487
2016-04-05    0.013096
2016-04-06    0.003171
2016-04-07    0.001400
Name: proportion, dtype: float64

**Observation - `date_crawled`**: 
The data shows that the crawler was active daily from early March to early April 2016. The distribution of crawls is relatively uniform across this month-long period.

In [9]:
# Analyzing the distribution of ad_created
print("Ad Created Distribution (Top 20):")
print(autos['ad_created'].str[:10].value_counts(normalize=True, dropna=False).sort_index().head(20))

Ad Created Distribution (Top 20):
ad_created
2015-06-11    0.000021
2015-08-10    0.000021
2015-09-09    0.000021
2015-11-10    0.000021
2015-12-05    0.000021
2015-12-30    0.000021
2016-01-03    0.000021
2016-01-07    0.000021
2016-01-10    0.000041
2016-01-13    0.000021
2016-01-14    0.000021
2016-01-16    0.000021
2016-01-22    0.000021
2016-01-27    0.000062
2016-01-29    0.000021
2016-02-01    0.000021
2016-02-02    0.000041
2016-02-05    0.000041
2016-02-07    0.000021
2016-02-08    0.000021
Name: proportion, dtype: float64

**Observation - `ad_created`**: 
While most ads were created during the crawling period (March–April 2016), there are some older ads dating back to late 2015. These older ads are quite rare, representing a very small percentage of the total dataset.

In [10]:
# Analyzing the distribution of last_seen
print("Last Seen Distribution:")
print(autos['last_seen'].str[:10].value_counts(normalize=True, dropna=False).sort_index())

Last Seen Distribution:
last_seen
2016-03-05    0.001071
2016-03-06    0.004324
2016-03-07    0.005395
2016-03-08    0.007413
2016-03-09    0.009595
2016-03-10    0.010666
2016-03-11    0.012375
2016-03-12    0.023783
2016-03-13    0.008895
2016-03-14    0.012602
2016-03-15    0.015876
2016-03-16    0.016452
2016-03-17    0.028086
2016-03-18    0.007351
2016-03-19    0.015834
2016-03-20    0.020653
2016-03-21    0.020632
2016-03-22    0.021373
2016-03-23    0.018532
2016-03-24    0.019767
2016-03-25    0.019211
2016-03-26    0.016802
2016-03-27    0.015649
2016-03-28    0.020859
2016-03-29    0.022341
2016-03-30    0.024771
2016-03-31    0.023783
2016-04-01    0.022794
2016-04-02    0.024915
2016-04-03    0.025203
2016-04-04    0.024483
2016-04-05    0.124761
2016-04-06    0.221806
2016-04-07    0.131947
Name: proportion, dtype: float64

**Observation - `last_seen`**: 
The `last_seen` column tells us when the crawler last recorded the ad, which likely indicates when a car was sold (and the ad removed). Interestingly, the last three days (April 5–7) show a massive spike in "last seen" values. This spike is likely due to the crawling period ending, rather than a sudden explosion in car sales.

In [11]:
# Analyzing registration_year
print("Registration Year Statistics:")
autos["registration_year"].describe()

Registration Year Statistics:

count    48565.000000
mean      2004.755421
std         88.643887
min       1000.000000
25%       1999.000000
50%       2004.000000
75%       2008.000000
max       9999.000000
Name: registration_year, dtype: float64

**Observation - `registration_year`**: 
The `registration_year` column contains significant errors:
* The **minimum** year is `1000`, which is long before cars existed.
* The **maximum** year is `9999`, which is far into the future.
These are clearly incorrect data points that will need to be cleaned in the next step.

## 7. Dealing with Incorrect Registration Year Data

As noted in the previous step, the `registration_year` column contains several inaccuracies that will bias our analysis. 

**Deciding the Bounds:**
* **Upper Bound**: Since the data was crawled in **2016**, any registration year above 2016 is physically impossible (a car cannot be registered after the ad was already seen).
* **Lower Bound**: While the first cars were invented in the late 1800s, it is highly unlikely that a significant number of listings on eBay Kleinanzeigen are for cars from that era. We will set the lower bound at **1900**.

Let's check what percentage of our data falls outside the **1900–2016** range to determine if we can safely remove them.

In [12]:
# Check how many rows are outside the 1900-2016 range
out_of_range = autos[~autos["registration_year"].between(1900, 2016)]
print(f"Number of invalid rows: {out_of_range.shape[0]}")
print(f"Percentage of invalid rows: {(out_of_range.shape[0] / autos.shape[0]) * 100:.2f}%")

# Filter the dataframe to keep only valid registration years
autos = autos[autos["registration_year"].between(1900, 2016)]

# Calculate the distribution of the remaining values
print("\nTop 10 Registration Years (Normalized):")
print(autos["registration_year"].value_counts(normalize=True).head(10))

Number of invalid rows: 1884
Percentage of invalid rows: 3.88%

Top 10 Registration Years (Normalized):
registration_year
2000    0.067608
2005    0.062895
1999    0.062060
2004    0.057904
2003    0.057818
2006    0.057197
2001    0.056468
2002    0.053255
1998    0.050620
2007    0.048778
Name: proportion, dtype: float64

### Observations on Registration Years

By removing the invalid years, we only lost about **3.9%** of the data, which is acceptable for maintaining the integrity of our analysis.

**Key Findings:**
* Most of the vehicles were registered within the last 20 years (specifically the **late 1990s to late 2000s**).
* The years **2000, 2005, and 1999** are the most common registration years in the dataset.
* This distribution aligns with what we would expect from a used car market, where the majority of listings are for relatively modern vehicles rather than vintage collectibles.

## 8. Exploring Price by Brand

Now that the data is clean, we can explore how different car brands compare in terms of pricing. We will focus our analysis on brands that represent a significant portion of the market. 

First, let's look at the market share of each brand.

In [13]:
# Calculate the percentage of listings for each brand
brand_counts = autos["brand"].value_counts(normalize=True)
print(brand_counts)

# Select brands that represent more than 5% of the total listings
common_brands = brand_counts[brand_counts > 0.05].index
print("\nSelected Brands for Aggregation:", common_brands)

brand
volkswagen        0.211264
bmw               0.110045
opel              0.107581
mercedes_benz     0.096463
audi              0.086566
ford              0.069900
renault           0.047150
peugeot           0.029841
fiat              0.025642
seat              0.018273
skoda             0.016409
nissan            0.015274
mazda             0.015188
smart             0.014160
citroen           0.014010
toyota            0.012703
hyundai           0.010025
sonstige_autos    0.009811
volvo             0.009147
mini              0.008762
mitsubishi        0.008226
honda             0.007840
kia               0.007069
alfa_romeo        0.006641
porsche           0.006127
suzuki            0.005934
chevrolet         0.005698
chrysler          0.003513
dacia             0.002635
daihatsu          0.002506
jeep              0.002271
subaru            0.002142
land_rover        0.002099
saab              0.001649
jaguar            0.001564
daewoo            0.001500
trabant           0.001392
rover             0.001328
lancia            0.001071
lada              0.000578
Name: proportion, dtype: float64

Selected Brands for Aggregation: Index(['volkswagen', 'bmw', 'opel', 'mercedes_benz', 'audi', 'ford'], dtype='object', name='brand')

### Selection Strategy
The top 6 brands in the dataset all have a market share greater than 5%. **Volkswagen** is by far the most popular brand, nearly doubling the share of the next most frequent brands, **BMW** and **Opel**. 

We will limit our aggregation to these top 6 brands (Volkswagen, BMW, Opel, Mercedes Benz, Audi, and Ford) to ensure our mean prices are based on a large enough sample size to be representative.

In [14]:
# Create an empty dictionary to store aggregate data
brand_mean_prices = {}

# Loop over the selected brands
for brand in common_brands:
    # Subset the dataframe for the specific brand
    brand_only = autos[autos["brand"] == brand]
    # Calculate the mean price
    mean_price = brand_only["price"].mean()
    # Store in dictionary
    brand_mean_prices[brand] = int(mean_price)

# Display the results
brand_mean_prices

{'volkswagen': 5402,
 'bmw': 8332,
 'opel': 2975,
 'mercedes_benz': 8628,
 'audi': 9336,
 'ford': 3749}

### Analysis of Results
From the aggregated price data, we can observe a clear "price tier" among the top brands:

* **Luxury Tier**: **Audi**, **BMW**, and **Mercedes Benz** are the most expensive, with average prices between **\$8,000 and \$9,000**.
* **Mid Tier**: **Volkswagen** sits in the middle with an average price of around **\$5,400**. This likely explains its massive popularity, as it offers a balance of quality and affordability.
* **Budget Tier**: **Ford** and **Opel** are the most affordable options, with average prices between **\$3,000** and **\\$3,700**.

This suggests that even in the used car market, premium branding significantly influences the listing price.

## 9. Storing Aggregate Data in a DataFrame

While we have identified a price gap between luxury and budget brands, we don't yet know if this is driven by the condition of the cars (such as mileage) or purely by brand value. 

In this step, we will calculate the average mileage for the top 6 brands and combine both the mean price and mean mileage into a single DataFrame. This will allow us to easily compare the two metrics side-by-side.

In [15]:
# Create an empty dictionary for mean mileage
brand_mean_mileage = {}

# Calculate mean mileage for the top brands
for brand in common_brands:
    brand_only = autos[autos["brand"] == brand]
    mean_mileage = brand_only["odometer_km"].mean()
    brand_mean_mileage[brand] = int(mean_mileage)

# Convert both dictionaries to Series objects
mean_price_series = pd.Series(brand_mean_prices)
mean_mileage_series = pd.Series(brand_mean_mileage)

# Create a DataFrame from the mean_price_series
brand_info = pd.DataFrame(mean_price_series, columns=['mean_price'])

# Assign the mean_mileage_series as a new column
brand_info['mean_mileage'] = mean_mileage_series

# Display the combined data
brand_info

               mean_price  mean_mileage
volkswagen           5402        128707
bmw                  8332        132572
opel                 2975        129310
mercedes_benz        8628        130788
audi                 9336        129157
ford                 3749        124266

### Analysis of Price vs. Mileage

By comparing the average price and mileage across the top brands, we can draw the following conclusions:

* **Consistent Mileage**: Interestingly, the average mileage for all these brands is very similar, falling mostly between **128,000 km and 130,000 km**. 
* **Brand Value Over Condition**: Despite the luxury brands (Audi, BMW, and Mercedes-Benz) having similar or even slightly higher mileage than the budget brands (Opel and Ford), they still command a much higher average price.
* **The Premium Gap**: For example, **Audi** has a higher average mileage than **Opel**, yet its average price is nearly **3 times higher**.

This confirms that the price differences we observed earlier are primarily driven by brand prestige and original market positioning rather than the luxury cars being in "newer" condition than the budget ones.

## 9. Further Cleaning and Final Analysis

To conclude the project, we will perform two additional tasks:
1.  **Translating German Categories**: Several columns use German terms (e.g., `manuell` for manual). We will map these to English to make the dataset accessible to a wider audience.
2.  **Damage Analysis**: We will compare the average price of cars with unrepaired damage versus those that have been repaired or have no damage.

In [16]:
# Check unique values in gearbox and fuel_type
print("Gearbox unique values:", autos["gearbox"].unique())
print("Fuel type unique values:", autos["fuel_type"].unique())

# Define mapping dictionaries
gearbox_map = {
    'manuell': 'manual',
    'automatik': 'automatic'
}

fuel_type_map = {
    'benzin': 'petrol',
    'diesel': 'diesel',
    'lpg': 'lpg',
    'pöl': 'vegetable_oil',
    'hybrid': 'hybrid',
    'elektro': 'electric',
    'andere': 'other'
}

# Apply mappings
autos["gearbox"] = autos["gearbox"].map(gearbox_map)
autos["fuel_type"] = autos["fuel_type"].map(fuel_type_map)

# Verify translation
autos[["gearbox", "fuel_type"]].head()

Gearbox unique values: ['manuell' 'automatik' nan]
Fuel type unique values: ['lpg' 'benzin' 'diesel' nan 'cng' 'hybrid' 'elektro' 'andere']

     gearbox fuel_type
0     manual       lpg
1  automatic    petrol
2     manual    petrol
3  automatic    petrol
4     manual    petrol

In [17]:
# First, translate the values to English
damage_map = {
    'ja': 'yes',
    'nein': 'no'
}
autos["unrepaired_damage"] = autos["unrepaired_damage"].map(damage_map)

# Now run the aggregation
damage_impact = autos.groupby("unrepaired_damage")["price"].mean()

print("Average Price based on Damage Status:")
print(damage_impact)

price_diff = damage_impact['no'] - damage_impact['yes']
print(f"\nCars without damage are, on average, ${price_diff:.2f} more expensive.")

Average Price based on Damage Status:
unrepaired_damage
no     7164.033103
yes    2241.146035
Name: price, dtype: float64

Cars without damage are, on average, $4922.89 more expensive.

## 10. Final Conclusion

Through this project, we cleaned a messy dataset of 50,000 eBay car listings. Key takeaways include:

* **Brand Value**: Premium German brands like Audi, BMW, and Mercedes-Benz maintain high resale values regardless of having similar mileage to budget brands like Opel.
* **Price Outliers**: Removing \$0 listings and extreme luxury "placeholders" (over \$350,000) was essential for a realistic mean price calculation.
* **Condition Matters**: As expected, cars with **unrepaired damage** are significantly cheaper (often by several thousand dollars) than those that are damage-free.
* **Market Dominance**: Volkswagen remains the "people's car" in Germany, dominating the market share by a wide margin.

The dataset is now clean, translated, and ready for more advanced machine learning or predictive modeling.